---
- name: Install php deps
  become_method: sudo
  apt:
    name:
      - php7.0
      - php7.0-mbstring
      - libapache2-mod-php7.3
  tags: install-package

- name: Download php-pam
  get_url:
    url: https://svwh.dl.sourceforge.net/project/openmediavault/packages/pool/main/p/php-pam/php-pam_1.0.3-2_armhf.deb
    dest: /tmp/php-pam_1.0.3-2_armhf.deb
    mode: 755

- name: Install php-pam
  become_method: sudo
  apt:
    deb: /tmp/php-pam_1.0.3-2_armhf.deb
  tags: install-package

- name: Install openmediavault keyring
  become_method: sudo
  apt:
    name: "{{ OMV_keyring }}"
    allow_unauthenticated: yes
    state: present
    force: yes
  tags: install-package

- name: Install openmediavault packages and tools
  become_method: sudo
  apt:
    name: "{{ OMV_packages }}"
    allow_unauthenticated: yes
    state: present
    force: yes
  notify: "Reboot omv node"
  tags: install-package

# - name: download file (openmediavault-omvextrasorg_latest_all.deb)
#   get_url:
#     url: http://omv-extras.org/openmediavault-omvextrasorg_latest_all4.deb
#     dest: /tmp/openmediavault-omvextrasorg_latest_all4.deb
#
# - name: Download and install omv-extras deb package
#   become_method: sudo
#   apt:
#     deb: "/tmp/openmediavault-omvextrasorg_latest_all4.deb"
#     allow_unauthenticated: yes
#     force: yes
#     update_cache: yes
#   tags: extra

#Config server
# - name: Enable ssh access to omv
#   shell: "omv-config -m /config/services/ssh/enable 1"
#   tags: enable_ssh

- name: Enable ssh service on boot
  service:
    name: ssh
    enabled: yes
    state: started
  tags: enable_ssh



# - name: Enable extra packages
#   shell: "omv-config --modify /config/system/omvextrasorg/{{ item }} 1"
#   with_items: '{{ OMV_repos }}'
#   tags: OMV_repos
#
# - name: Rebuild omvextrasorg config
#   shell: "omv-mkconf omvextrasorg"
#   tags: OMV_repos
#
# - name: Run ovm-aptclean
#   shell: "omv-aptclean"
#   tags: OMV_repos

# - name: Reboot omv node
#   become: yes
#   shell: sleep 2 && shutdown -r now
#   async: 1
#   poll: 0
#   ignore_errors: true
#   tags: reboot
#
# - name: Waiting for omv node to come back
#   become: false
#   local_action:
#     wait_for
#     host={{ ansible_default_ipv4.address }}
#     state=started
#     delay=30
#     timeout=60
#   tags: reboot

# - name: Install openmediavault plugins
#   become_method: sudo
#   apt:
#     name: "{{ plugins_packages }}"
#     state: present
#     force: yes
#   tags: install-plugins
